### ISSUE TITLE
On Auth: "This version of robinhood is no longer supported..."

### ISSUE THREAD

**Issue by robbalian** [torreyleonard/algotrader#25]
Looks like Robinhood has changed their API, and I'm getting this issues:

"This version of Robinhood is no longer supported. Please update your app or use Robinhood for Web to log in to your account."

Looks like there's a fix in for it, any chance we can merge: Gillinghammer-patch-2 ?

**Comment by jmangel** [comment]
Any update on this?

**Comment by liamitus** [comment]
Would also like to see this merged in but in the meantime you can install with the branch like so:
`npm i torreyleonard/algotrader#Gillinghammer-patch-2 --save`

**Comment by torreyleonard** [comment]
Merged #34 and published in v2.5.2.

Thank you!
